server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moviehub
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

moviehub:
  jwt:
    secret: bW92aWVodWJTZWNyZXRLZXkyMDI1ISQjJUBeJiomKCkrPT0xMjM0NTY3ODlhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejAxMjM0NTY3ODk=
    expiration: 86400 # 24 hours in seconds

logging:
  level:
    "[com.moviehub]": DEBUG
